version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bookstore_db
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore123
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: